apiVersion: v1
kind: Service
metadata:
  name: todo-app-broadcaster-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app-broadcaster
  ports:
    - name: http
      port: 3541
      targetPort: 3541