apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
  namespace: default
  labels:
    app: dummysite-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller
      containers:
      - name: controller
        image: docker.io/mmucahit0/dummysite-controller:latest
        imagePullPolicy: Always
        args:
        - --namespace=default
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi