apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: read-output-http-route
  namespace: exercises
spec:
  parentRefs:
  - name: log-output-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /readoutput
    backendRefs:
    - name: read-output-svc
      port: 2347