apiVersion: v1
kind: Service
metadata:
  name: read-output-node-port-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: log-output-deployment 
  ports:
    - port: 2347
      protocol: TCP
      targetPort: ${READ_OUTPUT_PORT}