apiVersion: v1
kind: Service
metadata:
  name: read-output-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: log-output-deployment 
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 4002