apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ping-pong-http-route
  namespace: exercises
spec:
  parentRefs:
  - name: log-output-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /pingpong
    backendRefs:
    - name: ping-pong-stset-svc
      port: 2346
  - matches:
    - path:
        type: PathPrefix
        value: /pings
    backendRefs:
    - name: ping-pong-stset-svc
      port: 2346