apiVersion: v1
kind: Service
metadata:
  name: ping-pong-deployment-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ping-pong-deployment 
  ports:
    - port: 2346
      protocol: TCP
      targetPort: ${PING_PONG_PORT}