apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-pong-stset
  namespace: exercises
spec:
  serviceName: ping-pong-stset-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-stset
  template:
    metadata:
      labels:
        app: ping-pong-stset
    spec:
      containers:
        - name: ping-pong-db
          image: ${DOCKER_REGISTRY}/ping_pong_db:amd64-v1
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - name: ping-pong-data-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: ping-pong-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 100Mi