apiVersion: v1
kind: Service
metadata:
  name: ping-pong-serverless-stset-db-svc
  namespace: exercises
  labels:
    app: ping-pong-serverless-stset-db
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: ping-pong-serverless-stset