apiVersion: v1
kind: Service
metadata:
  name: log-output-node-port-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: log-output-deployment 
  ports:
    - port: 2345
      protocol: TCP
      targetPort: ${LOG_OUTPUT_PORT}