apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-configmap
  namespace: exercises
data:
  message: "hello world"
  information_file_name: information.txt
  information.txt: |
    this text is from file