apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-deployment
  template:
    metadata:
      labels:
        app: log-output-deployment
    spec:
      volumes:
        - name: log-output-config-vol
          configMap:
            name: log-output-configmap
        - name: shared-log-file
          emptyDir: {}
        - name: shared-files
          persistentVolumeClaim:
            claimName: shared-claim
        
      containers:
        - name: log-output-container
          image: DOCKER_REGISTRY/log_output:amd64-v1
          imagePullPolicy: Always
          volumeMounts:
          - name: log-output-config-vol  
            mountPath: "/config"
          - name: shared-log-file
            mountPath: /usr/src/app/files
          - name: shared-files
            mountPath: /usr/src/app/shared_files
          env:
            - name: LOG_OUTPUT_PORT
              value: "4000"
            - name: LOG_FILE_PATH
              value: "/usr/src/app/files/log.txt"
            - name: PING_PONG_URL
              value: "http://ping-pong-svc:2346"
            - name: INFORMATION_FILE_NAME
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: information_file_name
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: message
          ports:
            - name: http
              containerPort: 4000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"  
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
        - name: read-output-container
          image: DOCKER_REGISTRY/read_output:amd64-v1
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-log-file
            mountPath: /usr/src/app/files
          env:
            - name: READ_OUTPUT_PORT
              value: "4002"
            - name: LOG_FILE_PATH
              value: "/usr/src/app/files/log.txt"
          ports:
            - name: http
              containerPort: 4002
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"  
