apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: log-output-gateway
  namespace: exercises
spec:
  gatewayClassName: istio
  listeners:
  - name: log-output-listener
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute