apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: log-output-rewrite-routes
  namespace: exercises
spec:
  parentRefs:
  - name: log-output-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ping-pong-svc
          port: 2346
    - matches:
        - path:
            type: PathPrefix
            value: /pings
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ping-pong-svc
          port: 2346
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: log-output-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /logoutput
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /logoutput
      backendRefs:
        - name: log-output-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /readoutput
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /readoutput
      backendRefs:
        - name: read-output-svc
          port: 2347