apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
- namespace.yaml
- config_map.yaml
- persistent_volume_claim.yaml
- deployment.yaml
- gateway.yaml
- log_output_service.yaml
- read_output_service.yaml
- log_output_http_route.yaml
- read_output_http_route.yaml
- ping_pong_deployment.yaml
- ping_pong_statefulset.yaml
- ping_pong_service.yaml
- ping_pong_headless_service.yaml
- ping_pong_cluster_ip_service.yaml
- ping_pong_http_route.yaml
- greeter-v1-deployment.yaml
- greeter-v2-deployment.yaml
- greeter-svc.yaml
- greeter-svc-1.yaml
- greeter-svc-2.yaml
- greeter-http-route.yaml

images:
- name: DOCKER_REGISTRY/log_output
  newName: docker.io/mmucahit0/log_output
  newTag: arm64-v1
- name: DOCKER_REGISTRY/ping_pong
  newName: docker.io/mmucahit0/ping_pong
  newTag: arm64-v1
- name: DOCKER_REGISTRY/ping_pong_db
  newName: docker.io/mmucahit0/ping_pong_db
  newTag: arm64-v1
- name: DOCKER_REGISTRY/read_output
  newName: docker.io/mmucahit0/read_output
  newTag: arm64-v1
- name: DOCKER_REGISTRY/greeter
  newName: docker.io/mmucahit0/greeter
