apiVersion: v1
kind: Service
metadata:
  name: ping-pong-stset-lb-svc
  namespace: exercises
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: ping-pong-stset
  ports:
    - port: 80
      protocol: TCP
      targetPort: ${PING_PONG_PORT}