apiVersion: v1
kind: Service
metadata:
  name: ping-pong-node-port-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: ping-pong-stset 
  ports:
    - port: 2346
      protocol: TCP
      targetPort: ${PING_PONG_PORT}