apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-configmap
  namespace: project
data:
  TODO_APP_PORT: "4000"
  TODO_APP_BACKEND_PORT: "4001"
  RANDOM_IMAGE_PATH: "/app/files/image.jpeg"
  TODO_APP_BACKEND_DB_URL: "postgres://todo_user:todo_password@todo-stset-db-svc:5432/todo_db" 
  NATS_URL: "nats://nats:4222"