apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-broadcaster-deployment
  namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-app-broadcaster
  template:
    metadata:
      labels:
        app: todo-app-broadcaster
    spec:
      containers:
        - name: todo-app-broadcaster-container
          image: TODO_APP_BROADCASTER_IMAGE/TAG
          imagePullPolicy: Always
          volumeMounts:
            - name: todo-app-config-vol 
              mountPath: "/config"
          env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: DISCORD_WEBHOOK_URL 
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: NATS_URL 
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            initialDelaySeconds: 10 
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3541
          livenessProbe:
            initialDelaySeconds: 20 
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3541
      volumes:
        - name: todo-app-config-vol
          configMap:
            name: todo-app-configmap