apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      containers:
        - name: todo-app-backend-container
          image: TODO_APP_BACKEND_IMAGE/TAG
          imagePullPolicy: Always
          volumeMounts:
            - name: todo-app-config-vol 
              mountPath: "/config"
          env:
            - name: TODO_APP_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: TODO_APP_BACKEND_PORT
            - name: TODO_APP_BACKEND_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: TODO_APP_BACKEND_DB_URL 
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: todo-app-config-vol
          configMap:
            name: todo-app-configmap