apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-app-backend-hpa
  namespace: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app-backend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80