apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-stset
  namespace: project
spec:
  serviceName: todo-app-stset-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-stset
  template:
    metadata:
      labels:
        app: todo-app-stset
    spec:
      containers:
        - name: todo-app-container
          image: TODO_APP_IMAGE/TAG
          volumeMounts:
            - name: todo-app-config-vol 
              mountPath: "/config"
          env:
            - name: TODO_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: TODO_APP_PORT
            - name: RANDOM_IMAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: RANDOM_IMAGE_PATH 
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"           
        - name: todo-app-backend-container
          image: TODO_APP_BACKEND_IMAGE/TAG
          volumeMounts:
            - name: todo-app-config-vol 
              mountPath: "/config"
          env:
            - name: TODO_APP_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: TODO_APP_BACKEND_PORT
            - name: TODO_APP_BACKEND_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: TODO_APP_BACKEND_DB_URL 
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"           
        - name: todo-app-backend-db
          image: TODO_APP_BACKEND_DB_IMAGE/TAG
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: todo-app-data-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: todo-app-config-vol
          configMap:
            name: todo-app-configmap
  volumeClaimTemplates:
    - metadata:
        name: todo-app-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo  # GKE default storage class (use "local-path" for k3d)
        resources:
          requests:
            storage: 100Mi