apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-stset
  namespace: project
spec:
  serviceName: todo-stset-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-stset
  template:
    metadata:
      labels:
        app: todo-app-stset
    spec:
      containers:
        - name: todo-app-backend-db
          image: TODO_APP_BACKEND_DB_IMAGE/TAG
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: todo-app-data-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  volumeClaimTemplates:
    - metadata:
        name: todo-app-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo  # GKE default storage class (use "local-path" for k3d)
        resources:
          requests:
            storage: 100Mi