apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-app-add-cronjob
  namespace: project
spec:
  schedule: "0 * * * *" # every hour at minute 0
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-app-add-cronjob
            image: TODO_APP_ADD_JOB_IMAGE/TAG
            env:
              - name: TODO_APP_BACKEND_DB_URL
                value: "postgres://todo_user:todo_password@todo-stset-db-svc:5432/todo_db"
          restartPolicy: OnFailure